language: android
jdk: oraclejdk21
dist: xenial
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3
    - ANDROID_HOME=~/android-sdk
    # PROGLOVE_URL
    - secure: VqcMEAP6b35VCjrIgRJdGEjnokcdD8cb6gJxoDsRMRFiSMW42A4AE/arknP/diweGjjKzYEr7o/1VUwKPmCbiTNB+9BE2UNUXNuvRZe6BAPo09TmONGRakG9eyidWza8cRjLP1tWlNof80DdaJATBe14Tp8ygXn4VjMV26GtEslcF7QdcC3d7NRPJCdGo4T2nFhfZlA7RELvCBiVXZOCQ3OFELeeTap8VI5M5FrxTwzQNoBT2+fHH92fHdY684oUBlXiml5IUAAa4AgohGsa7WuHILo9Id4AtMCISLfV+oBPgd0Gy0cz8P+7OXkfvoIQkOgosEeIhM3JVzxQrUMmOktgZWPVpuyGJskucxs6Ck1PLImKiGUB9buWfTZ/SRjpu26dMtK1zAlhKZI6AQf/gFQwsaiWvDsFjgOothkKxYIpUxpnZe/5GjhDtkC7EhXH9AHY7RCMspLA+paRcHlLJT/1XxjwfqBN9c/TAatTkg+3GHyT9nCLgex9CAvSiite/3pJk9zqXqJBVPv+GvH+I4IyDVSnN7y86rBG49/sIruWf6r16vZWbCmVgsTiv8GPGo4OrwTBVk9k3vqiJ2FunyiK6JsMFimcD7RBe5NJKMPVtrPrWk3Z4PAXUEEYdHF1sHZIirpCS6sitiUyueOlFEzAbltfrikfs48BDAvCHg8=
before_install:
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME
  - $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
  # Replacing the public repo url with the alpha repo url. The url must contain a entitlement token
  - sed -i "s,url \".*\",url \"$PROGLOVE_URL\",g" build.gradle.kts
jobs:
  include:
    - stage: build
      if: type = "pull_request" OR branch = development
      script:
        - "./gradlew assembleDebug"
    - stage: deploy
      if: branch = master AND type != "pull_request"
      script:
        - "./gradlew assembleDebug"
      deploy:
        - provider: script
          script: "./scripts/publish_code.sh"
          skip_cleanup: true
          on:
            repo: workaroundgmbh/pg_api_android_examples_private
            branch: master
